### ISSUE TITLE
Incorrect content type on release notes for 0.8.x

### ISSUE THREAD

**Issue by snorfalorpagus** [drone/docs#325] opened 2018-03-03 13:29 UTC
When I click the links for the 0.8.3 or 0.8.4 release notes on docs.drone.io they try to download, rather than displaying a page. The 0.7 and 0.6 release notes work as expected. The problem seems to be the content type header returned from the server. I'm not sure what's special about these files as the others in the documentation return the correct header.

```
(python36) C:\Users\Snorfalorpagus>curl -I http://docs.drone.io/release-0.7.0
HTTP/1.1 200 OK
x-amz-id-2: kOtVFNdqTZA3wca3jAvQv+TZ/zX5WosYtDgcblwuFDt7QasOQ1rtsVfwd/RmrgCu0a3mAw3DciQ=
x-amz-request-id: 3664FDE2515B0FDA
Date: Sat, 03 Mar 2018 13:26:01 GMT
Last-Modified: Wed, 28 Feb 2018 19:11:48 GMT
ETag: "359b8d26de99fb9d4b99c7ba1701d7dd"
Content-Type:
Content-Length: 10575
Server: AmazonS3


(python36) C:\Users\Snorfalorpagus>curl -I http://docs.drone.io/release-0.8.4
HTTP/1.1 200 OK
x-amz-id-2: E/HfekKxu+ZD7pcSp0JtvPB3ejMhDtXCxld3U/ot7isVu4Wbn/zPu7xGjYUHBGqQONRcqy6SWnw=
x-amz-request-id: B3AB78514E505408
Date: Sat, 03 Mar 2018 13:26:08 GMT
Last-Modified: Wed, 28 Feb 2018 19:11:48 GMT
ETag: "83b7b0305546b4dedd630d202c3fdbeb"
Content-Type: application/x-troff-man
Content-Length: 9287
Server: AmazonS3
```

**Comment by tboerger** [comment] 2018-03-03 14:29
Duplicate of https://github.com/drone/docs/issues/300 and since it's not resolved the issue should be reopened.

**Comment by tphoney** [comment] 2021-07-06 11:36
releases are no longer part of the docs site. closing this

**Closed by tphoney** 2021-07-06 11:36 UTC
